name: Build rnacos on gnu2.17 x86_64

on:
  workflow_dispatch:
    inputs:
      rnacosTag:
        type: string
        description: rnacos release tag
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "RNACOS Tags: $RNACOS_TAG"
          echo "RNACOS Tags: ${{ github.event.inputs.rnacosTag }}"
        env:
          RNACOS_TAG: ${{ inputs.rnacosTag }}

      - name: Clone r-nacos repository
        uses: actions/checkout@v4
        with:
          repository: nacos-group/r-nacos
          ref: ${{ github.event.inputs.rnacosTag }}
          path: r-nacos

      - name: Cache cargo registry
        id: cache-cargo-registry
        uses: actions/cache@v4
        env:
          cache-name: cache-cargo-registry
        with:
          path: |
            .cargo/git
            .cargo/registry
            ~/.cargo/git
            ~/.cargo/registry
            /opt/rust/cargo/git
            /opt/rust/cargo/registry
          key: ${{ runner.os }}-registry-${{ env.cache-name }}-${{ hashFiles('r-nacos/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-registry-${{ env.cache-name }}-
            ${{ runner.os }}-registry-

      - name: Cache cargo target
        id: cache-cargo-target
        uses: actions/cache@v4
        env:
          cache-name: cache-cargo-target
        with:
          path: r-nacos/target
          key: ${{ runner.os }}-target-${{ env.cache-name }}-${{ hashFiles('r-nacos/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-target-${{ env.cache-name }}-
            ${{ runner.os }}-target-

      - uses: brightx/rust-gnu2.17-action@1.91
        with:
          args: build --release --bins
          directory: r-nacos

      - name: Archive binary
        run: |
          cd r-nacos/target/release
          pwd
          cp ../../doc/conf/.env.example .env
          ls -alh
          tar czvf ../../../rnacos-x86_64-unknown-linux-gnu2.17-${{ github.event.inputs.rnacosTag }}.tar.gz rnacos .env
          cd -
      - name: Upload binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rnacos-x86_64-unknown-linux-gnu2.17-${{ github.event.inputs.rnacosTag }}
          path: |
            *.tar.gz
            *.zip
